# docker-compose config for rr-web project
# useful commands:
#   docker-compose up -d
#   docker-compose down
#   docker ps
#   docker exec -it rr-web sh
# web-site url: http://localhost:5003/
version: '3'

services:

  rr-web:
    container_name: rr-web
    image: node:10.15.0-alpine
    command: npm run docker-start
    working_dir: /home/app
    volumes:
      - .:/home/app/
    ports:
      - "5003:5000"
    depends_on:
      - rr-postgres
    restart: always
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:rrpasswd@rr-postgres/rrweb

  rr-postgres:
    container_name: rr-postgres
    image: postgres:9.6.2-alpine
    restart: always
    volumes:
       - ./var/pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rrweb
      POSTGRES_PASSWORD: rrpasswd
      PGDATA: /var/lib/postgresql/data
